cask_args appdir: "~/Applications", fontdir: "~/Library/Fonts"

tap "buo/cask-upgrade"
tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"

brew "ansible"
brew "bash"
brew "coreutils"
brew "curl-openssl"
brew "git"
brew "gnu-sed"
brew "ripgrep"
brew "jq"
brew "less"
brew "make"
brew "mas"
brew "ncurses"
brew "neovim"
brew "nmap"
brew "node"
brew "openssl"
brew "python"
brew "python3"
brew "reattach-to-user-namespace"
brew "rsync"
brew "ruby"
brew "shellcheck"
brew "stow"
brew "tmux"
brew "weechat"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "iterm2"
cask "karabiner-elements"
cask "keepingyouawake"
cask "minikube"
cask "slack"

mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sip", id: 507257563
